### ISSUE TITLE
OpenRTMプラグインの導入ができない

### ISSUE THREAD

**Issue by TTRist** [choreonoid/choreonoid#17]
windows10にて、最新のchoreonoid開発版にOpenRTMプラグイン導入を考えています。
開発版のドキュメント(https://choreonoid.org/ja/documents/latest/install/build-windows.html#id8)やopenRTMプラグイン(https://github.com/OpenRTM/choreonoid-openrtm)を参照してインストール作業を行いました。
choreonoidにcmakeを行う段階で「ENABLE_CORBA」を追加できず、openRTMプラグイン導入がうまくいきいません。
最新のchoreonoid開発版では、openRTMプラグインの導入はできなくなってしまったのでしょうか。
またプラグイン側にはfor OpenRTM-aist 1.1.2とありますが、最新バージョンのOpenRTM-aist 1.2.2に対応していますか。

**Comment by s-nakaoka** [comment]
申し訳ありませんが、現在のChoreonoid開発チーム（主に株式会社コレオノイドの開発者で構成）ではOpenRTMプラグインはサポートしておりません。Choreonoid掲示板の以下のトピックにありますように、OpenRTMプラグインのサポートは産総研のOpenRTM開発チームに引き継がれています。
https://discourse.choreonoid.org/t/openrtm/363

恐らくこのこともご理解の上で、choreonoid-openrtmリポジトリのissueでお問い合わされたものの、そちらで回答が無いということのようですね。
https://github.com/OpenRTM/choreonoid-openrtm/issues/7

私の方から勝手なことを申し上げられませんが、想像するに、現在の産総研のOpenRTM開発チームにおいてはこのプラグインのサポートまで手が回っていないものと思われます。私はそちらのメンバーではありませんので、あくまで想像ですが…。残念ながら放置状態になっている可能性があります。

OpenRTMプラグインもMITライセンスのオープンソースソフトウェアですので、どなたでも開発を引き継ぐことは可能です。他にプラグインの開発を引き継いでくれるところがあればよいのですが、そうでない場合は、ご自分で対応されるしかないかもしれません。

Choreonoid開発チームとしてはROS対応を進めておりますので、そちらの利用もご検討いただければと思います。ご期待に沿えず申し訳ありませんが、何卒ご了承ください。
