### ISSUE TITLE
Camera device cannot get image in SimpleController

### ISSUE THREAD

**Issue by TakashiSato** [choreonoid/choreonoid#20]
# Issue overview

Since the following commit, Camera device cannot get image properly in SImpleController.
 9d70912e10c47962baa927ba65c6cc98840ce181
(This issue was confirmed in the latest commit 2fe1349c007ddcb0a914e8df6226b0f316e8506f as well.)

# How to reproduce the issue

I added the following code to and tested the issue using `sample/tutorial/Tank/step6.cnoid`.

### sample/tutorial/CMakeLists.txt
```
24 + add_subdirectory(tutorial/Tank)
```

### sample/tutorial/Tank/CameraController.cpp
``` cpp
24    virtual bool control() override
25    {
26        printf("Camera name [%s] empty: %d, width: %d, height: %d\n",
27            camera->name().c_str(), camera->constImage().empty(), camera->constImage().width(), camera->constImage().height());
...
```

The console output after the simulation starts is as follows.
```
Camera name [Kinect] empty: 1, width: 0, height: 0
Camera name [Kinect] empty: 1, width: 0, height: 0
Camera name [Kinect] empty: 1, width: 0, height: 0
Camera name [Kinect] empty: 1, width: 0, height: 0
...
```

# Issue analysis

After investigating from the commit diffs, I guessed that the problem is related to the "copyStateFrom" function in `src/Body/Camera.cpp`, which used to copy the image.
https://github.com/choreonoid/choreonoid/commit/9d70912e10c47962baa927ba65c6cc98840ce181#diff-8966906dbbf119146333a766406604c2583e8b6d22b8071b6e1b2da14c8a3be3L69

This image copying process is done after copyCameraStateFrom, but within copyCameraStateFrom, the decision to copy an image is made based on the boolean value of `isImageStateClonable`.
https://github.com/choreonoid/choreonoid/commit/9d70912e10c47962baa927ba65c6cc98840ce181#diff-8966906dbbf119146333a766406604c2583e8b6d22b8071b6e1b2da14c8a3be3L86-L90

Debugging shows that the value of `isImageStateClonable` is always `False` in the default configuration of Tank/step6 .cnoid.
Therefore, the image is not copied in copyCameraStateFrom above, but in the previous commit code,  the image was then copied in copyStateFrom and SimpleController was able to properly get the image.

Further debugging shows that by changing the value of "Record vision data" in GLVisionSimulatorItem from `False` to `True` in the configuration of Tank/step6.cnoid, SimpleController can get image from the camera device even in the latest commit.

The following is the console output when the image is successfully acquired.
```
Camera name [Kinect] empty: 0, width: 320, height: 240
Camera name [Kinect] empty: 0, width: 320, height: 240
Camera name [Kinect] empty: 0, width: 320, height: 240
Camera name [Kinect] empty: 0, width: 320, height: 240
...
```

# Question

I'm not sure what the proper behavior to assume is, should we be able to get images from SimpleController only if "Record vision data" is `True`, as it was after commit 9d70912e10c47962baa927ba65c6cc98840ce181 ?
Or should we be able to get the image regardless of the value of "Record vision data" as was the case prior to the above commit?

**Comment by s-nakaoka** [comment]
Thank you very much for pointing out this problem. 
I'm sorry for the lack of confirmation at the time of the modification.
I will fix the problem, so please wait for a moment.

**Comment by TakashiSato** [comment]
I can confirm that the issue has been resolved and works fine in my environment too.
Thanks for your appropriate corrections!

> The property "record vision data" of GLVisionSimulatorItem is to record the vision data as a simulation log. If you enable this property, vision data such as camera image and range data is recorded as a part of the simulation log, and the data is reloaded to the corresponding sensor when you replay the simulation log. This property is disabled by default because the size of vision data is usually large and recording the data in every update frame could consume a huge amount of memory.

> On the other hand, the controller is what runs when the simulation is running, so it should be able to access the sensors regardless of the simulation log.

I understand the above very well. Thank you for your detailed explanation.

> I apologize for any inconvenience caused by this bug and thank you for your cooperation in correcting it.

No problem at all.
If I find any more problems, etc., I will be happy to cooperate again.
