### ISSUE TITLE
rotor inertia in mass matrix computation

### ISSUE THREAD

**Issue by th1991-01** [choreonoid/choreonoid#26]
Hi,

In the mass matrix computation, rotor inertia seems added twice.
Firstly, as a part of computing mass matrix, the inverse dynamics computation to obtain `A_G * delta_i + b_G` considers rotor inertia, as seen at https://github.com/choreonoid/choreonoid/blob/master/src/Body/InverseDynamics.cpp#L66.
Secondly, rotor inertia is also added at https://github.com/choreonoid/choreonoid/blob/master/src/Body/MassMatrix.cpp#L93.

typo comment?: motor inertia -> rotor inertia at https://github.com/choreonoid/choreonoid/blob/master/src/Body/MassMatrix.cpp#L93.

**Comment by s-nakaoka** [comment]
Thank you for pointing out this problem.
I have fixed this problem in f13000a77ff964dcc977d8f15eb71fab30bd0e8e .

> typo comment?: motor inertia -> rotor inertia at https://github.com/choreonoid/choreonoid/blob/master/src/Body/MassMatrix.cpp#L93.

A motor basically consists of a rotor and a reduction gear. The term "motor" is probably used here to mean a value that includes the factor of the reduction gear.
