### ISSUE TITLE
Choreonoid-1.7.0-win64.exe

### ISSUE THREAD

**Issue by arthurson** [choreonoid/choreonoid#28]
hello everyone, i am one of people who has nothing idea how to comply the software by themselves.

i searched the post there is .exe for windows user, but the lastest one is 1.5 ver. only.

since the 1.7 has been released for 3yrs already, will it be possible to provide 1.7.exe so more newbie can try this software with ease ?

thx everyone in advance.

**Comment by ssr-yuki** [comment]
We apologize that the develop team is currently not afford to distribute the Windows EXE file for the latest version.

Instead, we publish a document describing how to build and install Choreonoid from source. Please visit the link: https://choreonoid.org/en/documents/latest/install/build-windows.html

**Comment by arthurson** [comment]
actually i tried many time to complied and faced many difficutlties, that the reason asking for .exe
maybe some of people like me who bought premaid ai previously just wanna learn how to control their first robot, it seems finding the workable software is not an easy task for us.

**Comment by ssr-yuki** [comment]
Although we cannot provide the Windows EXE of Choreonoid soon, we can help you if you describe what happens in your environment. Thank you for your interest.
